// This file was autogenerated by /Users/Adam/code/build-stuff/node_modules/mantri/lib/../node_modules/closure-tools/closure-bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('js/app.js', ['app'], ['app.models.Person']);
goog.addDependency('js/models/model.js', ['app.models.Model'], []);
goog.addDependency('js/models/person.js', ['app.models.Person'], ['app.models.Model']);
